---
- name: Install FreeSwitch
  yum:
    name: kazoo-freeswitch
    state: latest
  notify: Gracefully Restart FreeSwitch

- name: Stop and Disable Default FreeSwitch
  service:
    name: freeswitch
    state: stopped
    enabled: no

- name: Create Kazoo Configuration
  template:
    src: kazoo.conf.xml.j2
    dest: /etc/kazoo/freeswitch/autoload_configs/kazoo.conf.xml
  notify: Gracefully Restart FreeSwitch

- name: Create FreeSwitch SIP Profile
  template:
    src: sipinterface_1.xml.j2
    dest: /etc/kazoo/freeswitch/sip_profiles/sipinterface_1.xml
  notify: Gracefully Restart FreeSwitch

- name: Create FreeSwitch Service
  copy:
    src: files/kazoo-freeswitch.service
    dest: /lib/systemd/system/kazoo-freeswitch.service

- name: Start and Enable FreeSwitch
  service:
    name: kazoo-freeswitch
    state: started
    daemon_reload: yes
    enabled: yes

- name: Allow FreeSwitch SIP TCP
  firewalld:
    port: 11000/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Allow FreeSwitch SIP UDP
  firewalld:
    port: 11000/udp
    permanent: true
    immediate: true
    state: enabled

- name: Allow FreeSwitch RTP
  firewalld:
    port: 16384-32768/udp
    permanent: true
    immediate: true
    state: enabled

